### ISSUE TITLE
Feature: Automatic Formatting

### ISSUE THREAD

**Issue by iamclaytonray** [lifechurch/melos#15]
Would you accept a PR that utilizes [Prettier](https://prettier.io/)? If so, any rules right off bat?

**Comment by tcg** [comment]
Thanks for the suggestion! 

I've been utilizing some stricter ESLint + Prettier formatting rules on a couple internal repos more recently, but we aren't yet settled on them as a team. 

I'm hoping to have a YV-specific ESLint ruleset soon, so that future JS projects can more simply `extends: "youversion-js"` or some such. 

I know the current ESLint config extends AirBNB and then changes some rules (https://github.com/lifechurch/melos/blob/d3c0b8b93cf97009426274e37f2eea4955a5bc39/.eslintrc.js) but it may be pretty well out-dated.
